version: '3.8'
services:
  cglt-node:
    image: ethereum/client-go:v1.13.15
    ports:
      - "127.0.0.1:8545:8545"
      - "127.0.0.1:8546:8546"
    entrypoint: ["/bin/sh", "/scripts/start.sh"]
    volumes:
      - ./data:/root/.ethereum
      - ./genesis.json:/genesis.json
      - ./scripts:/scripts
      - ./password.txt:/root/.ethereum/password.txt
